apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applications/snapshot-controller-crds.yaml
  - applications/snapshot-controller.yaml
  - applications/argocd.yaml
  - applications/cert-manager.yaml
  - applications/external-secrets.yaml
  - applications/metallb.yaml
  - applications/traefik.yaml
  - applications/longhorn.yaml
  - applications/velero.yaml
  - applications/cloudnative-pg.yaml
  - applications/keycloak-operator.yaml
  - applications/prometheus-operator-crds.yaml
  - applications/victoria-metrics-stack.yaml
  - applications/loki.yaml
  - applications/alloy.yaml
  - applications/blackbox-exporter.yaml
  - applications/forgejo.yaml
  - applications/jenkins.yaml
  - applications/headlamp.yaml
  - applications/platform-config.yaml
  - applications/workloads.yaml
