apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: oxisource-public
  namespace: oxisource-public
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: oxisource-public
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
      ports:
        - {protocol: TCP, port: 8080}
  egress: []
