extends: default
rules:
  line-length:
    max: 180
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
  comments:
    min-spaces-from-content: 1
  document-start: disable
  empty-lines:
    max-end: 1
ignore: |
  ansible/templates/
