all:
  children:
    k3s_servers:
      hosts:
        k3s-01:
          ansible_host: 192.168.60.10
          node_ip: 192.168.60.10
          wazuh_agent_group: linux-server
          zabbix_agent_group: linux
    wazuh_servers:
      hosts:
        sec1:
          ansible_host: 192.168.60.20
          zabbix_agent_group: linux
    zabbix_servers:
      hosts:
        ops1:
          ansible_host: 192.168.60.21
          zabbix_agent_group: linux
          wazuh_agent_group: linux-server
    proxmox_hosts:
      hosts:
        pve1:
          ansible_host: 192.168.20.10
          ansible_user: root
          wazuh_agent_group: proxmox
          zabbix_agent_group: linux
        pve2:
          ansible_host: 192.168.20.11
          ansible_user: root
          wazuh_agent_group: proxmox
          zabbix_agent_group: linux
    zabbix_agents:
      children:
        k3s_servers:
        wazuh_servers:
        proxmox_hosts:
        zabbix_servers:
    wazuh_agents:
      children:
        k3s_servers:
        proxmox_hosts:
        zabbix_servers:
  vars:
    ansible_user: mario
