apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db-recovery
  namespace: keycloak-recovery
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-standard-trixie
  bootstrap:
    recovery:
      source: keycloak-production
  externalClusters:
    - name: keycloak-production
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: keycloak-backups
          serverName: keycloak-db
  storage:
    storageClass: longhorn
    size: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "2"
      memory: 1Gi
  monitoring:
    enablePodMonitor: true
