apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: keycloak-backups
  namespace: keycloak-recovery
spec:
  configuration:
    destinationPath: s3://mmlinaric-homelab-keycloak/keycloak
    endpointURL: https://s3.de.io.cloud.ovh.net
    s3Credentials:
      accessKeyId:
        name: keycloak-recovery-s3
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: keycloak-recovery-s3
        key: ACCESS_SECRET_KEY
