apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-recovery-s3
  namespace: keycloak-recovery
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: keycloak-recovery-s3
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: 538fb79d-3f38-4435-8b2c-b4a001168856
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: 1b74a43c-2684-493c-bc09-b4a001169e82
