crds:
  enabled: true
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
resources:
  requests:
    cpu: 50m
    memory: 96Mi
  limits:
    cpu: 500m
    memory: 384Mi
webhook:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
cainjector:
  resources:
    requests:
      cpu: 25m
      memory: 96Mi
    limits:
      cpu: 250m
      memory: 384Mi

