apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-database
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: keycloak-database
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: 43808b34-e399-4f3e-9739-b4a0011bbf4a
    - secretKey: password
      remoteRef:
        key: b1db98b5-15f7-460b-aac7-b4a0011c13a4
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-superuser
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: keycloak-superuser
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: 02fc00f1-c8ab-4e43-88da-b4a0011ceffa
    - secretKey: password
      remoteRef:
        key: c9f2c8de-9ee0-4818-81ee-b4a0011c57e8
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-bootstrap-admin
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: keycloak-bootstrap-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: 340a0a6b-a000-4e82-8640-b4a0011c7745
    - secretKey: password
      remoteRef:
        key: a3b20167-c9c1-4a35-9c95-b4a0011c9a8f
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-barman-s3
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: keycloak-barman-s3
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: 538fb79d-3f38-4435-8b2c-b4a001168856
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: 1b74a43c-2684-493c-bc09-b4a001169e82
