apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-database
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: keycloak-database
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: CHANGE_ME_BWS_KEYCLOAK_DB_USERNAME_ID
    - secretKey: password
      remoteRef:
        key: CHANGE_ME_BWS_KEYCLOAK_DB_PASSWORD_ID
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-superuser
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: keycloak-superuser
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: CHANGE_ME_BWS_KEYCLOAK_PG_SUPERUSER_ID
    - secretKey: password
      remoteRef:
        key: CHANGE_ME_BWS_KEYCLOAK_PG_SUPERUSER_PASSWORD_ID
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-bootstrap-admin
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: keycloak-bootstrap-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: CHANGE_ME_BWS_KEYCLOAK_ADMIN_USERNAME_ID
    - secretKey: password
      remoteRef:
        key: CHANGE_ME_BWS_KEYCLOAK_ADMIN_PASSWORD_ID
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-barman-s3
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: keycloak-barman-s3
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: CHANGE_ME_BWS_KEYCLOAK_S3_ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: CHANGE_ME_BWS_KEYCLOAK_S3_SECRET_ACCESS_KEY_ID

