apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-runtime
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: jenkins-runtime
    creationPolicy: Owner
  data:
    - secretKey: oidc-client-secret
      remoteRef:
        key: 21a0a518-70fa-46ba-953b-b4a301259b63
    - secretKey: escape-hatch-username
      remoteRef:
        key: ff30c0e8-86f9-4d54-ac52-b4a30125e288
    - secretKey: escape-hatch-password
      remoteRef:
        key: 8278ff58-3918-41c2-858e-b4a301262ebe
