apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-runtime
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: jenkins-runtime
    creationPolicy: Owner
  data:
    - secretKey: oidc-client-secret
      remoteRef:
        key: 21a0a518-70fa-46ba-953b-b4a301259b63
    - secretKey: escape-hatch-username
      remoteRef:
        key: ff30c0e8-86f9-4d54-ac52-b4a30125e288
    - secretKey: escape-hatch-password
      remoteRef:
        key: 8278ff58-3918-41c2-858e-b4a301262ebe
    - secretKey: docker-agent-ssh-private-key
      remoteRef:
        key: cc7260d5-b364-4065-919e-b4a4008ba7b7
    - secretKey: forgejo-api-token
      remoteRef:
        key: 88984e97-a7c5-4523-b2b2-b4a800d66863
