cluster_name: homelab
cluster_timezone: Europe/Warsaw
k3s_version: v1.36.3+k3s1
helm_version: v4.2.3
kube_vip_version: v1.2.2

k3s_api_vip: 192.168.70.5
k3s_api_port: 6443
k3s_cluster_cidr: 10.42.0.0/16
k3s_service_cidr: 10.43.0.0/16
k3s_interface: ens18

argocd_chart_version: 10.3.0
cert_manager_chart_version: v1.21.1
external_secrets_chart_version: 2.9.0
gitops_repo_url: https://github.com/mmlinaric/homelab-k3s.git
gitops_repo_revision: main

bitwarden_organization_id: 4d8e230e-8a58-4810-95ac-b4480149e082
bitwarden_project_id: 832e95c1-00d7-460f-a5db-b4a00118089a

