apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-runtime
  namespace: gitlab
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: gitlab-runtime
    creationPolicy: Owner
  data:
    - secretKey: oidc-client-secret
      remoteRef:
        key: CHANGE_ME_BWS_GITLAB_OIDC_CLIENT_SECRET_ID
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-secrets-json
  namespace: gitlab
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: gitlab-secrets-json
    creationPolicy: Owner
  data:
    - secretKey: gitlab-secrets.json
      remoteRef:
        key: CHANGE_ME_BWS_GITLAB_SECRETS_JSON_ID
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-restic
  namespace: gitlab
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: gitlab-restic
    creationPolicy: Owner
  data:
    - secretKey: RESTIC_REPOSITORY
      remoteRef:
        key: CHANGE_ME_BWS_RESTIC_REPOSITORY_ID
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: CHANGE_ME_BWS_RESTIC_PASSWORD_ID
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: CHANGE_ME_BWS_RESTIC_S3_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: CHANGE_ME_BWS_RESTIC_S3_SECRET_ACCESS_KEY_ID

