apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-runtime
  namespace: gitlab
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: gitlab-runtime
    creationPolicy: Owner
  data:
    - secretKey: oidc-client-secret
      remoteRef:
        key: feeac2d4-049e-4cfa-9623-b4a0011ebc1c
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-secrets-json
  namespace: gitlab
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: gitlab-secrets-json
    creationPolicy: Owner
  data:
    - secretKey: gitlab-secrets.json
      remoteRef:
        key: e39b6984-399a-4ebc-b4bc-b4a0011f5589
