apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: argocd-oidc
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: clientSecret
      remoteRef:
        key: 591c7850-1525-433d-a994-b4a0012197b7
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
  namespace: argocd
spec:
  secretName: argocd-tls
  dnsNames: [argocd.mmlinaric.com]
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`argocd.mmlinaric.com`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
  tls:
    secretName: argocd-tls
