apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k3s-etcd-snapshot-s3-config
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: k3s-etcd-snapshot-s3-config
    creationPolicy: Owner
    template:
      type: etcd.k3s.cattle.io/s3-config-secret
      data:
        etcd-s3-endpoint: "{{ .endpoint }}"
        etcd-s3-access-key: "{{ .accessKey }}"
        etcd-s3-secret-key: "{{ .secretKey }}"
        etcd-s3-bucket: "{{ .bucket }}"
        etcd-s3-folder: homelab/etcd
        etcd-s3-region: "{{ .region }}"
  data:
    - secretKey: endpoint
      remoteRef:
        key: 10a96b58-3819-43f9-9db2-b4a001171df5
    - secretKey: accessKey
      remoteRef:
        key: a4405a55-23b8-4894-a88f-b4a00116bab6
    - secretKey: secretKey
      remoteRef:
        key: 6113609e-d682-4d74-b7be-b4a00116c9ff
    - secretKey: bucket
      remoteRef:
        key: 1a429142-9b22-44d9-ab3b-b4a00116ef01
    - secretKey: region
      remoteRef:
        key: f8681471-1722-4015-8b42-b4a001176dbc
