apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-db
  namespace: forgejo
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm,Delete=confirm
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-standard-trixie
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: forgejo-database
      encoding: UTF8
      localeCType: C.UTF-8
      localeCollate: C.UTF-8
  storage:
    storageClass: longhorn
    size: 20Gi
  resources:
    requests: {cpu: 100m, memory: 256Mi}
    limits: {cpu: 2, memory: 1Gi}
  monitoring:
    enablePodMonitor: true
