apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-database
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: forgejo-database
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: 9e618043-a265-438d-9946-b4a6012a9f73
    - secretKey: password
      remoteRef:
        key: fd854b42-92fd-478b-b9c5-b4a6012b803f
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-oidc
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: forgejo-oidc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        key: forgejo
        secret: "{{ .clientSecret }}"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: 4352a0ae-f749-4d05-b181-b4a601301d29
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-admin
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: forgejo-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: 307aef9d-9dde-4074-919b-b4a6013034ec
    - secretKey: password
      remoteRef:
        key: 7826cc33-39db-4398-bab1-b4a601306ab1
