apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-database
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: forgejo-database
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: 72d409d6-e9f0-48ae-82d2-b4a800bf83e8
    - secretKey: password
      remoteRef:
        key: aafcfed6-f6ab-4cb7-bc63-b4a800bf843f
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-oidc
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: forgejo-oidc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        key: forgejo
        secret: "{{ .clientSecret }}"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: 25375d80-608b-4fae-b70d-b4a800c2d8f7
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-admin
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: forgejo-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: b95a36b3-c4f6-455e-b7ca-b4a800bf8593
    - secretKey: password
      remoteRef:
        key: 3eecb57d-86de-42b6-b0f5-b4a800bf89c0
