apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: keycloak-db-recovery
    patch: |-
      - op: add
        path: /spec/bootstrap/recovery/recoveryTarget
        value:
          targetTime: "CHANGE_ME_RECOVERY_TARGET_RFC3339"
