---
- name: Restart Wazuh agent
  ansible.builtin.systemd_service:
    name: wazuh-agent
    state: restarted

- name: Reload audit rules
  ansible.builtin.command: augenrules --load
  changed_when: true
