apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dependency-track
  namespace: dependency-track
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dependency-track
      app.kubernetes.io/component: apiserver
  endpoints:
    - port: management
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
