apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.12.1
    helm:
      valuesObject:
        preUpgradeChecker:
          jobEnabled: true
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 1
          reclaimPolicy: Retain
        defaultSettings:
          defaultReplicaCount: 1
          defaultDataPath: /var/lib/longhorn
          storageOverProvisioningPercentage: 150
          storageMinimalAvailablePercentage: 15
          storageReservedPercentageForDefaultDisk: 20
          snapshotDataIntegrity: enabled
          snapshotDataIntegrityCronjob: 0 3 * * 0
        longhornUI:
          replicas: 1
        metrics:
          serviceMonitor:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
  ignoreDifferences:
    - group: longhorn.io
      kind: Node
      jsonPointers: [/spec/disks]
