apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.16.1
    helm:
      valuesObject:
        prometheus:
          serviceAccount: kube-prometheus-stack-prometheus
          namespace: monitoring
          serviceMonitor:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated: {enabled: true, prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
