apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/mmlinaric/homelab-k3s.git
    targetRevision: main
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {enabled: true, prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true, ServerSideApply=true, PruneLast=true]
    retry:
      limit: 10
      backoff: {duration: 10s, factor: 2, maxDuration: 3m}

